import Head from "next/head";
import { useState } from "react";
import styles from "../styles/Home.module.css";
import { useForm } from "react-hook-form";

export default function Home() {
	const { handleSubmit } = useForm();
	const [name, setName] = useState<string>("");

	return (
		<div className={styles.container}>
			<Head>
				<title>CICD test</title>
				<meta name="description" content="Generated by create next app" />
				<link rel="icon" href="/favicon.ico" />
			</Head>

			<main className={styles.main}>
				<h1 className={styles.title}>Save your name to MongoDB: </h1>

				<form
					onSubmit={handleSubmit(() => {
						console.log("handle submit");
					})}
				>
					<div>
						<input
							placeholder="Insert your name here..."
							value={name}
							required={true}
							type="text"
							onChange={(e) =>
								setName((e.currentTarget as HTMLInputElement).value)
							}
						/>
					</div>
					<button type="submit">Save</button>
				</form>
			</main>
		</div>
	);
}
